{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx-sftp.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressName := printf "%s-%s" $fullName .hostname }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nginx-sftp.name" . }}
    chart: {{ template "nginx-sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .hostname }}
      {{- if .tls.secretName }}
      secretName: {{ .tls.secretName }}
      {{- else }}
      secretName: {{ $ingressName }}-tls
      {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ $.Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" $.Values.service.ingressPort "context" $) | nindent 14 }}
  {{- end }}
{{- end }}
