{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx-sftp.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressName := printf "%s-%s" $fullName .hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nginx-sftp.name" . }}
    chart: {{ template "nginx-sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts }}
      secretName: {{ include "nginx-sftp.fullname" . }}-tls
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $.Values.ingress.pathType }}
            backend: 
              service:
                name: {{ $fullName }}
                port:
                  number: 8080
  {{- end }}
{{- end }}